export const lfcrPlayers = [
  {
    nickname: "Vayct",
    mahjongSoulId: "112893929",
    discordUserName: "vayct",
    team: "Evry",
  },
  {
    nickname: "Phokopi",
    mahjongSoulId: "119439982",
    discordUserName: "phokopi",
    team: "Evry",
  },
  {
    nickname: "Jinshia",
    mahjongSoulId: "100752739",
    discordUserName: "sileney",
    team: "Evry",
  },
  {
    nickname: "Alfouick",
    mahjongSoulId: "93897827",
    discordUserName: "alfouick",
    team: "Evry",
  },
  {
    nickname: "TlaseZ",
    mahjongSoulId: "133870434",
    discordUserName: "tlasez",
    team: "Evry",
  },
  {
    nickname: "Yossuze",
    mahjongSoulId: "132987751",
    discordUserName: "yossuze",
    team: "Evry",
  },
  {
    nickname: "_Savi_",
    mahjongSoulId: "129817959",
    discordUserName: "_savi__",
    team: "Evry",
  },
  {
    nickname: "procop",
    mahjongSoulId: "90248037",
    discordUserName: "procop.",
    team: "Evry",
  },
  {
    nickname: "Unebiere",
    mahjongSoulId: "77545578",
    discordUserName: "unebierreflorent",
    team: "Strasbourg",
  },
  {
    nickname: "walmslayer",
    mahjongSoulId: "104859753",
    discordUserName: "walmslayer",
    team: "Strasbourg",
  },
  {
    nickname: "azer67",
    mahjongSoulId: "139819746",
    discordUserName: "azer67",
    team: "Strasbourg",
  },
  {
    nickname: "Isabellerob",
    mahjongSoulId: "79017702",
    discordUserName: "isabelle7209",
    team: "Strasbourg",
  },
  {
    nickname: "Makeximus",
    mahjongSoulId: "126520549",
    discordUserName: "bmjmake_max",
    team: "Strasbourg",
  },
  {
    nickname: "阴阴南宁仙子",
    mahjongSoulId: "12291231",
    discordUserName: "Liccelso",
    team: "Lille",
  },
  {
    nickname: "Hamtagros",
    mahjongSoulId: "125891947",
    discordUserName: "chevalier_du_cancer",
    team: "Lille",
  },
  {
    nickname: "ふくろう",
    mahjongSoulId: "78368618",
    discordUserName: "Fukurou",
    team: "Lille",
  },
  {
    nickname: "greenie",
    mahjongSoulId: "106520033",
    discordUserName: "greeghost",
    team: "Lille",
  },
  {
    nickname: "Flyingaijin",
    mahjongSoulId: "122809446",
    discordUserName: "maelc1204",
    team: "Lille",
  },
  {
    nickname: "Hawat",
    mahjongSoulId: "125119205",
    discordUserName: "hawat8214",
    team: "Lille",
  },
  {
    nickname: "MeNeMeNs",
    mahjongSoulId: "127201381",
    discordUserName: "Menemens",
    team: "Lille",
  },
  {
    nickname: "Shinoseka",
    mahjongSoulId: "78294116",
    discordUserName: "oogwaykungfu_",
    team: "Lille",
  },
  {
    nickname: "Cey22",
    mahjongSoulId: "111731563",
    discordUserName: "cey7319",
    team: "Bourgoin",
  },
  {
    nickname: "YOOOOOOOOO",
    mahjongSoulId: "127171433",
    discordUserName: "yothisismahjong",
    team: "Bourgoin",
  },
  {
    nickname: "VerdaFenikso",
    mahjongSoulId: "122928099",
    discordUserName: "greenfenix",
    team: "Bourgoin",
  },
  {
    nickname: "SanGluten",
    mahjongSoulId: "110305379",
    discordUserName: "sangluten",
    team: "Bourgoin",
  },
  {
    nickname: "Goodlove",
    mahjongSoulId: "102703203",
    discordUserName: "goodlove6020",
    team: "Bourgoin",
  },
  {
    nickname: "TheReed",
    mahjongSoulId: "139758306",
    discordUserName: "thereed",
    team: "Bourgoin",
  },
  {
    nickname: "Theyo__",
    mahjongSoulId: "133595111",
    discordUserName: "valkyrja3272",
    team: "Bourgoin",
  },
  {
    nickname: "Camonigiri",
    mahjongSoulId: "132312039",
    discordUserName: "camillepollosson",
    team: "Bourgoin",
  },
  {
    nickname: "Gabibobax",
    mahjongSoulId: "129387623",
    discordUserName: "scaldingcoffeecup",
    team: "Bourgoin",
  },
  {
    nickname: "Azur67",
    mahjongSoulId: "114696046",
    discordUserName: "azureva",
    team: "Strasbourg",
  },
  {
    nickname: "Kwoin",
    mahjongSoulId: "93350506",
    discordUserName: "kwoin.kwoin",
    team: "StBrieuc",
  },
  {
    nickname: "regregnak",
    mahjongSoulId: "134080487",
    discordUserName: "Regregnak",
    team: "StBrieuc",
  },
  {
    nickname: "biline",
    mahjongSoulId: "120276587",
    discordUserName: "Emeline0834",
    team: "StBrieuc",
  },
  {
    nickname: "Narbolia",
    mahjongSoulId: "115173995",
    discordUserName: "narbolia",
    team: "Bourgoin",
  },
  {
    nickname: "MiyanagaTeru",
    mahjongSoulId: "119870958",
    discordUserName: "Callisto1497",
    team: "Mulhouse",
  },
  {
    nickname: "TokuraMisaki",
    mahjongSoulId: "117672814",
    discordUserName: "shota.kun_ellystitsu",
    team: "Mulhouse",
  },
  {
    nickname: "fingerdash",
    mahjongSoulId: "122277351",
    discordUserName: "fingerdash68",
    team: "Mulhouse",
  },
  {
    nickname: "InaExter",
    mahjongSoulId: "89507942",
    discordUserName: "Inaexter",
    team: "Mulhouse",
  },
  {
    nickname: "Nymphali66",
    mahjongSoulId: "84260965",
    discordUserName: "shosuromaru",
    team: "Mulhouse",
  },
  {
    nickname: "Piezuri",
    mahjongSoulId: "123017961",
    discordUserName: "dapiepiece",
    team: "Cannes",
  },
  {
    nickname: "Jimi",
    mahjongSoulId: "123438318",
    discordUserName: "zzimi_here",
    team: "Cannes",
  },
  {
    nickname: "Rizmo",
    mahjongSoulId: "123087470",
    discordUserName: "n7rizmo",
    team: "Cannes",
  },
  {
    nickname: "Shinki",
    mahjongSoulId: "117673198",
    discordUserName: "shinki.",
    team: "Cannes",
  },
  {
    nickname: "Dranato",
    mahjongSoulId: "123903587",
    discordUserName: "dranato",
    team: "Cannes",
  },
  {
    nickname: "Elentir",
    mahjongSoulId: "102991841",
    discordUserName: ".elentirnimaj",
    team: "StBrieuc",
  },
  {
    nickname: "Stelena",
    mahjongSoulId: "122924267",
    discordUserName: "yilia",
    team: "Toulouse",
  },
  {
    nickname: "Aliangel",
    mahjongSoulId: "112751595",
    discordUserName: "aliangel",
    team: "Toulouse",
  },
  {
    nickname: "Hugues",
    mahjongSoulId: "96731113",
    discordUserName: "onizuka_fr",
    team: "Toulouse",
  },
  {
    nickname: "Geroth",
    mahjongSoulId: "122939630",
    discordUserName: "geroth_irith",
    team: "Toulouse",
  },
  {
    nickname: "Satoji",
    mahjongSoulId: "122005358",
    discordUserName: "satosq",
    team: "Toulouse",
  },
  {
    nickname: "Roukanken",
    mahjongSoulId: "111017187",
    discordUserName: "vrai_gent",
    team: "Toulouse",
  },
  {
    nickname: "kartn",
    mahjongSoulId: "131417954",
    discordUserName: "kartenk",
    team: "Toulouse",
  },
  {
    nickname: "ミルチィ",
    mahjongSoulId: "85138918",
    discordUserName: ".tehblob",
    team: "Toulouse",
  },
  {
    nickname: "Metatheria",
    mahjongSoulId: "127073765",
    discordUserName: "metatheria",
    team: "Toulouse",
  },
  {
    nickname: "Mople",
    mahjongSoulId: "121747173",
    discordUserName: "mople",
    team: "Toulouse",
  },
  {
    nickname: "jeeks",
    mahjongSoulId: "90935781",
    discordUserName: "nikokushi",
    team: "Toulouse",
  },
  {
    nickname: "Smogo31000",
    mahjongSoulId: "82962917",
    discordUserName: "smogo31",
    team: "Toulouse",
  },
  {
    nickname: "anguigui",
    mahjongSoulId: "93517162",
    discordUserName: "anguigui",
    team: "Toulouse",
  },
  {
    nickname: "anhvu",
    mahjongSoulId: "81705194",
    discordUserName: "anh_vu_",
    team: "Toulouse",
  },
  {
    nickname: "Pianzi",
    mahjongSoulId: "126292846",
    discordUserName: "pianzi",
    team: "Toulouse",
  },
  {
    nickname: "Buwn",
    mahjongSoulId: "128582370",
    discordUserName: "nwub",
    team: "Toulouse",
  },
  {
    nickname: "Anh_",
    mahjongSoulId: "144042215",
    discordUserName: "_anh_",
    team: "Toulouse",
  },
  {
    nickname: "Teg_jong_31",
    mahjongSoulId: "89962982",
    discordUserName: "teg7901",
    team: "Toulouse",
  },
  {
    nickname: "RedKoiFish",
    mahjongSoulId: "115203307",
    discordUserName: "mentrek",
    team: "Union LVV",
  },
  {
    nickname: "Sandy71",
    mahjongSoulId: "124943470",
    discordUserName: "Sandy7169",
    team: "Union LVV",
  },
  {
    nickname: "Kirby_Dreamer",
    mahjongSoulId: "95446753",
    discordUserName: "ptitnico",
    team: "Union LVV",
  },
  {
    nickname: "Sakura28",
    mahjongSoulId: "88331749",
    discordUserName: "sarah.sakura.akaneko",
    team: "Union LVV",
  },
  {
    nickname: "Yaoshan",
    mahjongSoulId: "77422314",
    discordUserName: "Yaoshan",
    team: "Massalia",
  },
  {
    nickname: "zoltanz",
    mahjongSoulId: "119151982",
    discordUserName: "zoltanz13102",
    team: "Massalia",
  },
  {
    nickname: "DUAPHIN",
    mahjongSoulId: "111563758",
    discordUserName: "duaphin.",
    team: "Massalia",
  },
  {
    nickname: "Victrul",
    mahjongSoulId: "108853731",
    discordUserName: "Victrul",
    team: "Massalia",
  },
  {
    nickname: "Cecile13",
    mahjongSoulId: "112284005",
    discordUserName: "altaise",
    team: "Massalia",
  },
  {
    nickname: "DHZ",
    mahjongSoulId: "85230821",
    discordUserName: "Eld.io",
    team: "Massalia",
  },
  {
    nickname: "LucasC13",
    mahjongSoulId: "96487649",
    discordUserName: "lucascurci1_02251",
    team: "Massalia",
  },
  {
    nickname: "beaujolaisman",
    mahjongSoulId: "124774766",
    discordUserName: "Beaujolaisman",
    team: "Union LVV",
  },
  {
    nickname: "Dofetr0",
    mahjongSoulId: "105843553",
    discordUserName: "dofetro",
    team: "Union LVV",
  },
  {
    nickname: "Bast9",
    mahjongSoulId: "97298537",
    discordUserName: "echobrainsert",
    team: "Bordeaux",
  },
  {
    nickname: "Arrcival",
    mahjongSoulId: "114033006",
    discordUserName: "arrcival",
    team: "Bordeaux",
  },
  {
    nickname: "Makoas",
    mahjongSoulId: "114708078",
    discordUserName: "makoas",
    team: "Bordeaux",
  },
  {
    nickname: "muguette",
    mahjongSoulId: "111670887",
    discordUserName: ".muguette",
    team: "Bordeaux",
  },
  {
    nickname: "Anthonys01",
    mahjongSoulId: "122464485",
    discordUserName: "anthonys01",
    team: "Bordeaux",
  },
  {
    nickname: "anneso",
    mahjongSoulId: "81775082",
    discordUserName: "annso1212",
    team: "Villejuif",
  },
  {
    nickname: "CaroXiaojie8",
    mahjongSoulId: "115754350",
    discordUserName: "caroxiaojiecaroline",
    team: "Villejuif",
  },
  {
    nickname: "PititeMarion",
    mahjongSoulId: "89752172",
    discordUserName: "marionpapillon.",
    team: "Villejuif",
  },
  {
    nickname: "m4hj0ng4dd1ct",
    mahjongSoulId: "126875365",
    discordUserName: "cedric9575",
    team: "Villejuif",
  },
  {
    nickname: "Gladiateur",
    mahjongSoulId: "113446117",
    discordUserName: "gabrieldes",
    team: "Villejuif",
  },
  {
    nickname: "Arbogad",
    mahjongSoulId: "125146857",
    discordUserName: "arbogad",
    team: "Angers",
  },
  {
    nickname: "Lorio",
    mahjongSoulId: "125348329",
    discordUserName: "loriog",
    team: "Angers",
  },
  {
    nickname: "Tortue49",
    mahjongSoulId: "111931241",
    discordUserName: "patricia_4976",
    team: "Angers",
  },
  {
    nickname: "Bagdor",
    mahjongSoulId: "98391017",
    discordUserName: "bagdor",
    team: "Angers",
  },
  {
    nickname: "scratch",
    mahjongSoulId: "123267822",
    discordUserName: "scratchy49",
    team: "Angers",
  },
  {
    nickname: "Zatsu",
    mahjongSoulId: "116329710",
    discordUserName: "zatsu.",
    team: "Angers",
  },
  {
    nickname: "LuneBleue",
    mahjongSoulId: "113327470",
    discordUserName: "lunebleue22",
    team: "Angers",
  },
  {
    nickname: "あいさく",
    mahjongSoulId: "79286406",
    discordUserName: "aisaku",
    team: "Union RNP",
  },
  {
    nickname: "petitbleu",
    mahjongSoulId: "91417834",
    discordUserName: "mt_petitbleu",
    team: "Union RNP",
  },
  {
    nickname: "Yine",
    mahjongSoulId: "82920042",
    discordUserName: "angelo_maolet",
    team: "Union RNP",
  },
  {
    nickname: "Kaznad",
    mahjongSoulId: "102850665",
    discordUserName: "kaznad",
    team: "Union RNP",
  },
  {
    nickname: "Swell",
    mahjongSoulId: "119370606",
    discordUserName: "renlybara",
    team: "Union RNP",
  },
  {
    nickname: "Etosan",
    mahjongSoulId: "121694574",
    discordUserName: "nullpo_eto",
    team: "Union RNP",
  },
  {
    nickname: "Neilfrize",
    mahjongSoulId: "140862946",
    discordUserName: "neilfrize",
    team: "Union RNP",
  },
  {
    nickname: "Felixvercors",
    mahjongSoulId: "97754849",
    discordUserName: "felix01284",
    team: "Union RNP",
  },
  {
    nickname: "zessx",
    mahjongSoulId: "124838887",
    discordUserName: "zessx",
    team: "Union RNP",
  },
  {
    nickname: "Mel067",
    mahjongSoulId: "139956711",
    discordUserName: "melissalameche",
    team: "Union RNP",
  },
  {
    nickname: "Aluco",
    mahjongSoulId: "127260134",
    discordUserName: "alllucco",
    team: "Union RNP",
  },
  {
    nickname: "laurasanya",
    mahjongSoulId: "120179814",
    discordUserName: "pipluv",
    team: "Union RNP",
  },
  {
    nickname: "Aliuqa",
    mahjongSoulId: "111011174",
    discordUserName: "aliuqa",
    team: "Union RNP",
  },
  {
    nickname: "Moko79",
    mahjongSoulId: "89203046",
    discordUserName: "mok0",
    team: "Union RNP",
  },
  {
    nickname: "Elatheod",
    mahjongSoulId: "117676005",
    discordUserName: "melia.azedarach",
    team: "Union RNP",
  },
  {
    nickname: "Sting",
    mahjongSoulId: "120063342",
    discordUserName: "ix.sting",
    team: "Montpellier",
  },
  {
    nickname: "Kalaw",
    mahjongSoulId: "104196588",
    discordUserName: "kalaway",
    team: "Montpellier",
  },
  {
    nickname: "dehidehi",
    mahjongSoulId: "95790572",
    discordUserName: "dehidehidehi",
    team: "Montpellier",
  },
  {
    nickname: "Patrocle",
    mahjongSoulId: "138071522",
    discordUserName: "patrocle34_16034",
    team: "Montpellier",
  },
  {
    nickname: "DianD",
    mahjongSoulId: "129762663",
    discordUserName: "Car8line__",
    team: "Montpellier",
  },
  {
    nickname: "Nevine",
    mahjongSoulId: "108851683",
    discordUserName: "nandji974",
    team: "Reunion",
  },
  {
    nickname: "Shlikam",
    mahjongSoulId: "102261345",
    discordUserName: "Shlikam",
    team: "Reunion",
  },
  {
    nickname: "Ivanoten",
    mahjongSoulId: "103650785",
    discordUserName: "gruchka.",
    team: "Montpellier",
  },
  {
    nickname: "SteelTempura",
    mahjongSoulId: "84224486",
    discordUserName: "loupavecunp",
    team: "Montpellier",
  },
  {
    nickname: "Pitayasblancss",
    mahjongSoulId: "96255849",
    discordUserName: "pitayablanc974_17993",
    team: "Reunion",
  },
  {
    nickname: "Cordonier",
    mahjongSoulId: "87232362",
    discordUserName: "loic_.",
    team: "Paris",
  },
  {
    nickname: "Rorofy",
    mahjongSoulId: "84938218",
    discordUserName: "Rorofy",
    team: "Paris",
  },
  {
    nickname: "煎餅お兄さん",
    mahjongSoulId: "124792046",
    discordUserName: "Tinecro",
    team: "Paris",
  },
  {
    nickname: "Pommy",
    mahjongSoulId: "125167982",
    discordUserName: "kennylo4895",
    team: "Paris",
  },
  {
    nickname: "Benoit",
    mahjongSoulId: "123673582",
    discordUserName: "monsieurmyst",
    team: "Paris",
  },
  {
    nickname: "Alexapin",
    mahjongSoulId: "120273518",
    discordUserName: "alexapin",
    team: "Paris",
  },
  {
    nickname: "ccl",
    mahjongSoulId: "122888686",
    discordUserName: "ccl95",
    team: "Paris",
  },
  {
    nickname: "冬雪",
    mahjongSoulId: "111581038",
    discordUserName: "Shiraha6517",
    team: "Paris",
  },
  {
    nickname: "Dubrissaud",
    mahjongSoulId: "114028782",
    discordUserName: "Dubrissaud",
    team: "Paris",
  },
  {
    nickname: "Aksy",
    mahjongSoulId: "104875500",
    discordUserName: ".aksy.",
    team: "Paris",
  },
  {
    nickname: "Ewemax",
    mahjongSoulId: "130746855",
    discordUserName: "Ewemax",
    team: "Paris",
  },
  {
    nickname: "PoustouFlan",
    mahjongSoulId: "81233766",
    discordUserName: "PoustouFlan",
    team: "Paris",
  },
  {
    nickname: "Neral",
    mahjongSoulId: "125168357",
    discordUserName: "yamagawani",
    team: "Paris",
  },
  {
    nickname: "elfan",
    mahjongSoulId: "119193449",
    discordUserName: "Totoro4",
    team: "Reunion",
  },
  {
    nickname: "Ygardpaou",
    mahjongSoulId: "117668590",
    discordUserName: "ygardpaou",
    team: "Reunion",
  },
  {
    nickname: "Merky~",
    mahjongSoulId: "102717025",
    discordUserName: "soshy_squishy",
    team: "Montpellier",
  },
  {
    nickname: "LillieJ",
    mahjongSoulId: "82062054",
    discordUserName: "LillieJinx",
    team: "Reunion",
  },
  {
    nickname: "Flk974",
    mahjongSoulId: "81886694",
    discordUserName: "flk97450_52566",
    team: "Reunion",
  },
  {
    nickname: "kairymcr",
    mahjongSoulId: "80760293",
    discordUserName: "kairy3501",
    team: "Reunion",
  },
  {
    nickname: "Kcinairam",
    mahjongSoulId: "91831916",
    discordUserName: "mariamahjong",
    team: "Reunion",
  },
  {
    nickname: "beixoultes",
    mahjongSoulId: "89527914",
    discordUserName: "beixoultes",
    team: "Mulhouse",
  },
];
