import dotenv from "dotenv";

dotenv.config();

const {
  DISCORD_TOKEN,
  DISCORD_CLIENT_ID,
  DISCORD_GUILD_ID,
  MONGODB_URI,
  MAJSOUL_UID,
  MAJSOUL_TOKEN,
  NANIKIRU_SHEET_ID,
  MAJSOUL_AUTH_HEADER,
} = process.env;

if (
  !DISCORD_TOKEN ||
  !DISCORD_CLIENT_ID ||
  !DISCORD_GUILD_ID ||
  !MONGODB_URI ||
  !MAJSOUL_UID ||
  !MAJSOUL_TOKEN ||
  !NANIKIRU_SHEET_ID ||
  !MAJSOUL_AUTH_HEADER
) {
  throw new Error("Missing environment variables");
}

export const config = {
  DISCORD_TOKEN,
  DISCORD_CLIENT_ID,
  DISCORD_GUILD_ID,
  MONGODB_URI,
  MAJSOUL_UID,
  MAJSOUL_TOKEN,
  NANIKIRU_SHEET_ID,
  MAJSOUL_AUTH_HEADER,
};
